### ISSUE TITLE
dragen_sv_merge.py

### ISSUE THREAD

**Issue by JosephLalli** [srbehera/DRAGEN_Analysis#1]
Love it.

Do you have dragen_sv_merge.py available for interested individuals? Merging SNP datasets with SV datasets has been trickier than I imagined - it would be lovely if you have a solution!

-Joe

**Comment by srbehera** [comment]
Hi Joe,
We have not merged SNPs with SVs in our analysis. The `truvari_merge.sh` was used to merge STR, SV and CNVs.

-Sairam

**Comment by JosephLalli** [comment]
I must have misread, my apologies. At any rate, I would still be interested in seeing the dragen-sv_merge.py code referred to in the truvari_merge.sh script.

**Comment by srbehera** [comment]
No worries. I am sorry, it seems the dragen-sv_merge.py code is not uploaded. I will take care of that asap. Thanks for noticing that.

**Comment by srbehera** [comment]
@JosephLalli I have uploaded the `dragen_sv_merge.py` file. Some additional info can be found on `dragen_sv_merge_notes` file.

**Comment by jdidion** [comment]
@srbehera do you still recommend using `dragen_sv_merge.py` versus `truvari collapse`?

**Comment by srbehera** [comment]
@jdidion This script can be used to merge the different type of variant (SV, STR and CNV) vcfs generated by DRAGEN. I think the truvari collapse (https://github.com/ACEnglish/truvari/wiki/collapse) is designed for SV merging.
